      - name: Install Dependencies
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir -p www # هادي هي اللي كتحل بزاف ديال المشاكل
          echo '{"appId":"com.belrhazi.app","appName":"Belrhazi","webDir":"www","bundledWebRuntime":false}' > capacitor.config.json
          cp index.html www/ || true
